# permissions for end users to view postgreswriters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgres-writer-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgreswriter-viewer-role
rules:
- apiGroups:
  - testlery.testlery.com
  resources:
  - postgreswriters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testlery.testlery.com
  resources:
  - postgreswriters/status
  verbs:
  - get
